{{- if gt (int64 .Values.replicaCount) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  {{- if .Values.minAvailable }}
  minAvailable: {{ default "1" .Values.minAvailable }}
  {{- end }}
  {{- if and (not .Values.minAvailable) (.Values.maxUnavailable) }}
  maxUnavailable: {{ .Values.maxUnavailable }}
  {{- end }}
{{- end }}
